### PR TITLE
server: add support for extra bnode entries in BosConfig

### PR DESCRIPTION
**Pull request by rissson**

### CODE REVIEW

**Review by meffie — COMMENTED** [review]
Neat! Looks good! I will give it a try it before I merge.

**Comment by rissson** [comment]
Running in production here: https://gitlab.cri.epita.fr/cri/iac/infrastructure/-/commit/00b5b113781ea0358d06281274e477ec58a052f3

**Review by meffie — APPROVED** [review]
Thank you.

**Comment by rissson** [comment]
Thank you for your swift reviews!

**Comment by meffie** [comment]
On Wed, 01 Sep 2021 10:13:17 -0700
risson ***@***.***> wrote:

> Running in production here: https://gitlab.cri.epita.fr/cri/iac/infrastructure/-/commit/00b5b113781ea0358d06281274e477ec58a052f3

This is very cool! Thank you for sharing.

Would you be willing to do the galaxy survey for the OpenAFS collection? That could help with
adoption:

  https://galaxy.ansible.com/openafs_contrib/openafs


-- 
Michael Meffie ***@***.***>

**Comment by rissson** [comment]
I just did :D

**Comment by meffie** [comment]
On Mon, 13 Sep 2021 14:14:41 -0700
risson ***@***.***> wrote:

> I just did :D

High marks, Thanks!

-- 
Michael Meffie ***@***.***>

**Comment by rissson** [comment]
Only what's fair. Thank you for your work!

**Pull request merged**
